### ISSUE TITLE
ValueError: Invalid isoformat string

### ISSUE THREAD

**Issue by keinschoenerland** [merlinschumacher/libaudiothek#1]
What a nice Project! Thank you!
I just did "pip install sgqlc==16.0", and in folder libaudiothek/src I typed the following into the python shell:

```
from libaudiothek import *
a = Audiothek()
a.search("Krimi")
```
and it gave me:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/user/Dokumente/python/audiothek/libaudiothek/src/libaudiothek_merlinschumacher/libaudiothek.py", line 173, in search
    program_sets = self.__process_program_sets(
  File "/home/user/Dokumente/python/audiothek/libaudiothek/src/libaudiothek_merlinschumacher/libaudiothek.py", line 134, in __process_program_sets
    publish_date=datetime.fromisoformat(node.last_item_added),
ValueError: Invalid isoformat string: '2022-09-20T10:06:31.21693+02:00'
```
When I try something else after this (e.g. "TrueCrime"), my only answer is:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/user/Dokumente/python/audiothek/libaudiothek/src/libaudiothek_merlinschumacher/libaudiothek.py", line 152, in search
    search = op.search(query=term)
  File "/home/user/.local/lib/python3.10/site-packages/sgqlc/operation/__init__.py", line 1811, in __call__
    raise ValueError(
ValueError: search already have a selection search(query: "Krimi") {   (<- But this time I searched for "TrueCrime")
  items {
    nodes {
      id
      title
      publishDate
      ...
}. Maybe use __alias__ as param?
```
Am I doing something wrong?
Could you please give me a hint how to use libaudiothek?
Thanks a lot! :)

**Comment by merlinschumacher** [comment]
Hi and thank you!

I'm pretty much still getting this started, but I will look into it this week.

**Comment by merlinschumacher** [comment]
The issue should be fixed and there is a proper example in the readme now.

**Comment by keinschoenerland** [comment]
Ah thank you very much! 

First I got:
```
File "/home/user/Dokumente/python/audiothek/libaudiothek/src/libaudiothek/libaudiothek.py", line 11, in <module>
    from .audiothek_schema import audiothek_schema as schema
ImportError: attempted relative import with no known parent package
```
but after deleting the dot / changing corresponding line to:
`from audiothek_schema imort audiothek_schema as schema `

**it worked :D**
Maybe its because i just installed python without any "environment" etc.?

I'll start playing around with the library the next days... :) 
Thank you!
